### ISSUE TITLE
web view height issue

### ISSUE THREAD

**Issue by parmindersingh1** [TheFinestArtist/FinestWebView-Android#14]
There is a problem which happening to me is webpage is opened with lot of empty space below footer, this is not issue with website because i tested it on multiple sites same issue here is screenshot

![screenshot_2016-01-01-06-21-53](https://cloud.githubusercontent.com/assets/3261782/12069352/92fd8fde-b050-11e5-9810-34983d980ded.png)

there is more white space below the screenshot .
Same issue with finestwebview sample app, i think problem is webview height when we open a page with more height to small height the webview page height dont change

**Comment by avsector** [comment]
Experiencing the same issue.
When going to a website with less height, the content is filled in the container with more height, causing a blank space as the footer.

The height of WebView grows indefinitely if it is a child of nestedscrollview.
Seems like a regression in 23.1.1 support library. It was fixed in 22.2.1.

**Comment by TheFinestArtist** [comment]
@parmindersingh1 @mblcdr I think I fixed just by setting the minimum height of `WebViewLayout`.
But, I don't have way to make this bug again.

**Comment by TheFinestArtist** [comment]
@parmindersingh1 @mblcdr Released 1.1.5 and let me know if you guys have same problem!

**Comment by avsector** [comment]
Will do as soon as I get the chance.

**Comment by mc0239** [comment]
Still having this issue.. Tried visiting duckduckgo.com, same issue tested on Marshmallow and Kitkat versions. There a fix for it?
![screenshot](https://cloud.githubusercontent.com/assets/17457833/21518441/c702d63c-cce6-11e6-8a1e-425e72b33643.png)
